services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    container_name: swine-profiteer-app
    ports:
      - "3333:3333"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - DB_HOST=mysql
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - swine-network

  mysql:
    image: mysql:8.0
    container_name: swine-profiteer-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - swine-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: swine-profiteer-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - swine-network

volumes:
  mysql_data:

networks:
  swine-network:
    driver: bridge
