FROM node:20-alpine


WORKDIR /app


RUN apk add --no-cache \
    bash \
    git \
    && rm -rf /var/cache/apk/*


COPY package*.json ./

RUN npm install


COPY . .


RUN mkdir -p tmp


EXPOSE 3333


ENV NODE_ENV=development


CMD ["npm", "run", "dev"]
